# Generated by Django 5.2.8 on 2025-11-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Product', models.CharField(max_length=100)),
                ('Manufacture_part_Number', models.CharField(max_length=10, primary_key='True', serialize=False)),
                ('Manufacturing_Date', models.DateField()),
                ('Expiry_Date', models.DateField()),
                ('Price', models.FloatField()),
                ('Quantity', models.CharField(max_length=5)),
                ('Ingredients', models.TextField()),
            ],
        ),
    ]
